version: '3.8'

services:
  nestjs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: nestjs
    ports:
      - 3000:3000